version: "3.8"
services:
#Database service 1
  db:
    image: mysql:8.4
    container_name: devops_tracker_db
    restart: unless-stopped
#Here Setting Environment Variables
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#creating volume
    volumes:
      - mysql_data:/var/lib/mysql
#healthcheck of Database
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
#memory limit for database
    mem_limit: 512m
#network for database
    networks:
      - devops_network
#web service - backend ke liye
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: devops_tracker_web
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      db:
        condition: service_healthy
#memory limit for backend
    mem_limit: 256m
#network for backend
    networks:
      - devops_network
#ngnix service - reverse proxy ke liye
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: devops_tracker_nginx
    restart: unless-stopped
    ports:
      - "8082:80"
    depends_on:
      - web
#memory limit for nginx
    mem_limit: 128m
#network for nginx
    networks:
      - devops_network
#volumes create ke liye
volumes:
  mysql_data:
#network create ke liye
networks:
  devops_network:
    driver: bridge