apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: devtrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: mysql
          image: mysql:8.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: { name: db-secret, key: MYSQL_ROOT_PASSWORD }
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef: { name: db-secret, key: MYSQL_DATABASE }
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef: { name: db-secret, key: MYSQL_USER }
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef: { name: db-secret, key: MYSQL_PASSWORD }
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 10
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 60
            periodSeconds: 15
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc

