apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: devtrack
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30082        # compose ka 8082:80 ka replacement
  type: NodePort